name: PushLearn CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3'

      - name: Check IOS Devices
        run: xcrun simctl list devices
      
      - name: Build
        run: |
          xcodebuild \
            -project PushLearn.xcodeproj \
            -scheme PushLearn \
            -destination 'id=AE1B743D-A3CC-4A1E-BFC9-ED56C5BE12F5' \
            build

      - name: Test
        run: |
          xcodebuild \
            -project PushLearn.xcodeproj \
            -scheme PushLearn \
            -destination 'id=AE1B743D-A3CC-4A1E-BFC9-ED56C5BE12F5' \
            test
